### PR TITLE
use idc-index for IDCClient directly

### PR DESCRIPTION
**Pull request by vkt1414**
To address second task left on #15, I removed IDCClient.py as it will be imported from idc-index python package. Added a cursor to indicate while initializing IDCClient.

### CODE REVIEW

**Comment by fedorov** [comment]
Interesting error! 

image

**Comment by vkt1414** [comment]
I think I know exactly where the error (not a fatal one) is happening. The download works just fine but throws this error, because I wanted to stream the output of s5cmd download. But it may not be useful at all, so I'll comment it out.

**Comment by fedorov** [comment]
I have a bit better fix for it, hold on

**Comment by fedorov** [comment]
https://github.com/ImagingDataCommons/idc-index/pull/5

**Pull request merged**
